---
name: BUILD
on: [push, pull_request]

jobs:
  build_version:
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, macos-latest]
        os: [macos-latest]
        # os: [ubuntu-latest],
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: version
        run: echo "::set-output name=version::$(cat ./version.txt)"
        id: version
      - name: create stuff
        run: ls -alFR > a.txt
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: version.txt
        env:
          GITHUB_TOKEN: ${{ github.token }}
