---
name: RELEASE
on:
  push:
    tags:
      - '*'

jobs:
  - name: upload darwin artifact
    uses: actions/upload-release-asset@v1
    env:
      GITHUB_TOKEN: ${{ github.token }}
    with:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      asset_path: a.txt
      asset_name: a.txt
      # asset_content_type: application/gzip
      asset_content_type: text/plain

